from collections.abc import Sequence
from typing import Any, final

@final
class INESHeader:
    @property
    def chr_size(self, /) -> int: ...
    @property
    def prg_size(self, /) -> int: ...

@final
class Point:
    def __add__(self, other: object, /) -> Point: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __iter__(self, /) -> Any: ...
    def __new__(cls, /, x: int, y: int) -> Point: ...
    def copy(self, /) -> Point: ...
    @property
    def x(self, /) -> int: ...
    @x.setter
    def x(self, /, value: int) -> None: ...
    @property
    def y(self, /) -> int: ...
    @y.setter
    def y(self, /, value: int) -> None: ...

@final
class Rect:
    def __eq__(self, other: object, /) -> bool: ...
    def __iter__(self, /) -> Any: ...
    def __mul__(self, other: object, /) -> Rect: ...
    def __new__(cls, /, x: int = 0, y: int = 0, width: int = 0, height: int = 0) -> Rect: ...
    def bottom(self, /) -> int: ...
    def bottom_left(self, /) -> Point: ...
    def bottom_right(self, /) -> Point: ...
    def contains(self, /, other: Rect) -> bool: ...
    @property
    def height(self, /) -> int: ...
    @height.setter
    def height(self, /, value: int) -> None: ...
    def intersects(self, /, other: Rect) -> bool: ...
    def left(self, /) -> int: ...
    def point_in(self, /, x: int, y: int, include_borders: bool = True) -> bool: ...
    def right(self, /) -> int: ...
    def size(self, /) -> tuple[int, int]: ...
    def top(self, /) -> int: ...
    def top_left(self, /) -> Point: ...
    def top_right(self, /) -> Point: ...
    @property
    def width(self, /) -> int: ...
    @width.setter
    def width(self, /, value: int) -> None: ...
    @property
    def x(self, /) -> int: ...
    @x.setter
    def x(self, /, value: int) -> None: ...
    @property
    def y(self, /) -> int: ...
    @y.setter
    def y(self, /, value: int) -> None: ...

@final
class Rom:
    def __new__(cls, /, data: Sequence[int]) -> Rom: ...
    def byte(self, /, address: Any) -> int: ...
    def find_byte(self, /, byte: int, start: Any |None, end: Any |None) -> Any |None: ...
    @staticmethod
    def from_file(path: str) -> Rom: ...
    def little_endian(self, /, address: Any) -> int: ...
    def nibbles(self, /, address: Any) -> tuple[int, int]: ...
    def offset(self, /, address: Any) -> Any: ...
    @property
    def prg_banks(self, /) -> int: ...
    def prg_normalize(self, /, address: Any) -> Any: ...
    @property
    def prg_units(self, /) -> int: ...
    def read(self, /, address: Any, count: int) -> bytes: ...
    def read_until_byte(self, /, address: Any, byte: int) -> bytes |None: ...
    def save_to(self, /, path: str) -> None: ...
    def tsa_data_for_object_set(self, /, object_set_index: Any) -> bytes: ...
    def write(self, /, address: Any, data: bytes) -> None: ...
    def write_byte(self, /, address: Any, byte: int) -> None: ...
    def write_little_endian(self, /, address: Any, integer: int) -> None: ...
    def write_nibbles(self, /, address: Any, high_nibble: int, low_nibble: int) -> None: ...
    def write_offset(self, /, address: Any, offset: Any) -> None: ...

def clamp(min: int, value: int, max: int) -> int: ...
def hex_int(number: str) -> int: ...
