level_label_lo:
	.byte <Default_Level_0_0_generators
	.byte <Default_Level_1_1_generators
	.byte <Default_Level_2_2_generators
	.byte <Default_Level_3_3_generators
	.byte <Default_Level_4_4_generators
	.byte <Default_Level_5_5_generators
	.byte <Default_Level_6_6_generators
	.byte <Default_Level_7_7_generators
	.byte <Default_Level_8_8_generators
	.byte <Default_Level_9_9_generators
	.byte <Default_Level_10_10_generators
	.byte <Default_Level_11_11_generators
	.byte <Default_Level_12_12_generators
	.byte <Default_Level_13_13_generators
	.byte <Default_Level_14_14_generators
	.byte <Default_Level_15_15_generators
	.byte <Default_Level_16_16_generators
	.byte <Default_Level_17_17_generators
	.byte <Default_Level_18_18_generators
	.byte <Default_Level_19_19_generators
	.byte <Default_Level_20_20_generators
	.byte <Ship_W1_21_generators
	.byte <Ship_W2_22_generators
	.byte <Ship_W3_23_generators
	.byte <Ship_W4_24_generators
	.byte <Ship_W5_25_generators
	.byte <Ship_W6_26_generators
	.byte <Ship_W7_27_generators
	.byte <Crappy_Ship_W8_28_generators
	.byte <Kings_Room_W1_29_generators
	.byte <Kings_Room_W2_30_generators
	.byte <Kings_Room_W3_31_generators
	.byte <Kings_Room_W4_32_generators
	.byte <Kings_Room_W5_33_generators
	.byte <Kings_Room_W6_34_generators
	.byte <Kings_Room_W7_35_generators
	.byte <Kings_Room_W1_36_generators
	.byte <Coin_Ship_W1_37_generators
	.byte <Bonus_Game_W0_38_generators
	.byte <Bonus_Game_W0_39_generators
	.byte <Bonus_Level_W1_40_generators
	.byte <Bonus_Level_W2_41_generators
	.byte <Bonus_Level_W3_42_generators
	.byte <Bonus_Level_W4_43_generators
	.byte <Bonus_Level_W5_44_generators
	.byte <Bonus_Level_W6_45_generators
	.byte <Bonus_Level_W7_46_generators
	.byte <Bonus_Level_W8_47_generators
	.byte <Level_3_Ending_W5_48_generators
	.byte <Level_3_Ending_W5_49_generators
	.byte <Level_3_Ending_W5_50_generators
	.byte <Level_5_Ending_W4_51_generators
	.byte <Level_3_Ending_W5_52_generators
	.byte <Level_3_Ending_W5_53_generators
	.byte <Level_3_Ending_W5_54_generators
	.byte <Level_3_Ending_W5_55_generators
	.byte <Level_1_W1_generators
	.byte <Hammer_Bros_1_W1_generators
	.byte <Level_2_W1_generators
	.byte <Level_3_W1_generators
	.byte <Default_Level_86_generators
	.byte <Level_4_W1_generators
	.byte <Hammer_Bros_2_W1_generators
	.byte <Dungeon_W1_generators
	.byte <Kings_Room_W1_generators
	.byte <Level_5_W1_generators
	.byte <Level_6_W1_generators
	.byte <Hammer_Bros_1_W2_generators
	.byte <Level_2_W2_generators
	.byte <Level_3_W2_generators
	.byte <Level_1_W2_generators
	.byte <Dungeon_W2_generators
	.byte <Pipe_1_End_2_W2_generators
	.byte <Pipe_1_End_1_W2_generators
	.byte <Hidden_Hammer_Bros_W2_generators
	.byte <Level_4_W2_generators
	.byte <Quicksand_W2_generators
	.byte <Hammer_Bros_2_W2_generators
	.byte <Kings_Room_W2_generators
	.byte <Level_5_W2_generators
	.byte <Pyramid_Outside_Area_W2_generators
	.byte <Hammer_Bros_1_W3_generators
	.byte <Hammer_Bros_3_W3_generators
	.byte <Level_3_W3_generators
	.byte <Level_2_W3_generators
	.byte <Level_4_W3_generators
	.byte <Hammer_Bros_2_W3_generators
	.byte <Dungeon__1_W3_generators
	.byte <Level_1_W3_generators
	.byte <Hammer_Bros_4_W3_generators
	.byte <Pipe_1_End_2_W3_generators
	.byte <Level_5_W3_generators
	.byte <Pipe_1_End_1_W3_generators
	.byte <Pipe_2_End_1_W3_generators
	.byte <Level_6_W3_generators
	.byte <Level_7_W3_generators
	.byte <Level_8_W3_generators
	.byte <Dungeon__2_W3_generators
	.byte <Level_9_W3_generators
	.byte <Pipe_3_End_1_W3_generators
	.byte <Pipe_2_End_2_W3_generators
	.byte <Hidden_Hammer_Bros_W3_generators
	.byte <Kings_Room_W3_generators
	.byte <Pipe_3_End_2_W3_generators
	.byte <Hammer_Bros_1_W4_generators
	.byte <Pipe_1_End_1_W4_generators
	.byte <Level_6_W4_generators
	.byte <Kings_Room_W4_generators
	.byte <Dungeon__2_W4_generators
	.byte <Pipe_2_End_1_W4_generators
	.byte <Level_5_W4_generators
	.byte <Pipe_2_End_2_W4_generators
	.byte <Dungeon__1_W4_generators
	.byte <Level_3_Beginning_W4_generators
	.byte <Level_2_W4_generators
	.byte <Level_4_W4_generators
	.byte <Pipe_1_End_2_W4_generators
	.byte <Level_1_W4_generators
	.byte <Hammer_Bros_1_W5_generators
	.byte <Level_2_W5_generators
	.byte <Level_3_Beginning_W5_generators
	.byte <Level_1_W5_generators
	.byte <Default_Level_180_generators
	.byte <Default_Level_181_generators
	.byte <Tower__Part_1__W5_generators
	.byte <Dungeon__1_W5_generators
	.byte <Hammer_Bros_2_W5_generators
	.byte <Tower__Going_Down__W5_generators
	.byte <Hammer_Bros_3_W5_generators
	.byte <Level_5_W5_generators
	.byte <Hammer_Bros_4_W5_generators
	.byte <Level_4_W5_generators
	.byte <Dungeon__2_Beginning_End_W5_generators
	.byte <Level_7_W5_generators
	.byte <Kings_Room_W5_generators
	.byte <Level_9_W5_generators
	.byte <Level_8_W5_generators
	.byte <Level_6_W5_generators
	.byte <Hammer_Bros_2_W6_generators
	.byte <Level_2_W6_generators
	.byte <Hammer_Bros_1_W6_generators
	.byte <Pipe_1_End_2_W6_generators
	.byte <Level_1_W6_generators
	.byte <Dungeon__1_W6_generators
	.byte <Pipe_1_End_1_W6_generators
	.byte <Level_3_W6_generators
	.byte <Pipe_2_End_2_W6_generators
	.byte <Pipe_2_End_1_W6_generators
	.byte <Level_6_Outside_Area_W6_generators
	.byte <Dungeon__2_W6_generators
	.byte <Level_8_W6_generators
	.byte <Level_4_W6_generators
	.byte <Level_7_W6_generators
	.byte <Level_5_Outside_Area_W6_generators
	.byte <Level_9_Outside_Area_W6_generators
	.byte <Dungeon__3_W6_generators
	.byte <Kings_Room_W6_generators
	.byte <Level_10_W6_generators
	.byte <Hammer_Bros_1_W7_generators
	.byte <Pipe_2_End_2_W7_generators
	.byte <Pipe_5_End_2_W7_generators
	.byte <Dungeon__1_W7_generators
	.byte <Level_1_Outside_Area_W7_generators
	.byte <Pipe_1_End_1_W7_generators
	.byte <Pipe_5_End_1_W7_generators
	.byte <Pipe_8_End_1_W7_generators
	.byte <Piranha_Plant__1_W7_generators
	.byte <Pipe_1_End_2_W7_generators
	.byte <Pipe_2_End_1_W7_generators
	.byte <Level_4_Outside_Area_W7_generators
	.byte <Level_2_W7_generators
	.byte <Pipe_3_End_1_W7_generators
	.byte <Pipe_4_End_1_W7_generators
	.byte <Level_3_W7_generators
	.byte <Level_6_Outside_Area_W7_generators
	.byte <Level_7_Beginning_End_W7_generators
	.byte <Pipe_7_End_2_W7_generators
	.byte <Default_Level_257_generators
	.byte <Pipe_4_End_2_W7_generators
	.byte <Pipe_7_End_1_W7_generators
	.byte <Level_8_W7_generators
	.byte <Level_5_Outside_Area_W7_generators
	.byte <Default_Level_264_generators
	.byte <Pipe_8_End_2_W7_generators
	.byte <Level_9_W7_generators
	.byte <Dungeon__2_W7_generators
	.byte <Pipe_3_End_2_W7_generators
	.byte <Kings_Room_W7_generators
	.byte <Piranha_Plant__2_W7_generators
	.byte <Pipe_1_End_1_W8_generators
	.byte <Hidden_Level_W8_generators
	.byte <Pipe_2_End_1_W8_generators
	.byte <Tank__1_W8_generators
	.byte <Battleship_W8_generators
	.byte <Pipe_2_End_2_W8_generators
	.byte <Pipe_4_End_1_W8_generators
	.byte <Crappy_Ship_W8_generators
	.byte <Pipe_3_End_1_W8_generators
	.byte <Hand_Trap__3_W8_generators
	.byte <Hand_Trap__2_W8_generators
	.byte <Hand_Trap__1_W8_generators
	.byte <Pipe_1_End_2_W8_generators
	.byte <Pipe_4_End_2_W8_generators
	.byte <Pipe_6_End_1_W8_generators
	.byte <Level_1_W8_generators
	.byte <Dungeon_W8_generators
	.byte <Pipe_3_End_2_W8_generators
	.byte <Level_2_W8_generators
	.byte <Default_Level_298_generators
	.byte <Default_Level_299_generators
	.byte <Pipe_6_End_2_W8_generators
	.byte <Tank__2_W8_generators
	.byte <Bowser's_Castle_W8_generators
	.byte <Default_Level_305_213_generators
	.byte <Default_Level_306_214_generators
	.byte <Default_Level_307_215_generators
	.byte <Default_Level_308_216_generators
	.byte <Default_Level_309_217_generators
	.byte <Default_Level_310_218_generators
	.byte <Default_Level_311_219_generators
	.byte <Default_Level_312_220_generators
	.byte <Default_Level_313_221_generators
	.byte <Default_Level_314_222_generators
	.byte <Default_Level_315_223_generators
	.byte <Default_Level_316_224_generators
	.byte <Default_Level_317_225_generators
	.byte <Default_Level_318_226_generators
	.byte <Default_Level_319_227_generators
	.byte <Default_Level_320_228_generators
	.byte <Default_Level_321_229_generators
	.byte <Default_Level_322_230_generators
	.byte <Default_Level_323_231_generators
	.byte <Default_Level_324_232_generators
	.byte <Default_Level_325_233_generators
	.byte <Default_Level_326_234_generators
	.byte <Default_Level_327_235_generators
	.byte <Default_Level_328_236_generators
	.byte <Default_Level_329_237_generators
	.byte <Default_Level_330_238_generators
	.byte <Default_Level_331_239_generators
	.byte <Default_Level_332_240_generators
	.byte <Default_Level_333_241_generators
	.byte <Default_Level_334_242_generators
	.byte <Default_Level_335_243_generators
	.byte <Default_Level_336_244_generators
	.byte <Default_Level_337_245_generators
	.byte <Default_Level_338_246_generators
	.byte <Default_Level_339_247_generators
	.byte <Default_Level_340_248_generators
	.byte <Default_Level_341_249_generators
	.byte <Default_Level_342_250_generators
	.byte <Default_Level_343_251_generators
	.byte <Default_Level_344_252_generators
	.byte <Default_Level_345_253_generators
	.byte <Default_Level_346_254_generators
	.byte <Default_Level_347_255_generators
	.byte <Ship_Boss_Room_W1_generators
	.byte <Ship_Boss_Room_W2_generators
	.byte <Ship_Boss_Room_W3_generators
	.byte <Ship_Boss_Room_W4_generators
	.byte <Ship_Boss_Room_W5_generators
	.byte <Ship_Boss_Room_W6_generators
	.byte <Ship_Boss_Room_W7_generators
	.byte <Crappy_Ship_Boss_Room_W8_generators
	.byte <Anchors_Away_W1_generators
	.byte <Ship_W1_generators
	.byte <Anchors_Away_W2_generators
	.byte <Ship_W2_generators
	.byte <Anchors_Away_W3_generators
	.byte <Ship_W3_generators
	.byte <Anchors_Away_W4_generators
	.byte <Ship_W4_generators
	.byte <Anchors_Away_W5_generators
	.byte <Ship_W5_generators
	.byte <Anchors_Away_W6_generators
	.byte <Ship_W6_generators
	.byte <Anchors_Away_W7_generators
	.byte <Ship_W7_generators
	.byte <Coin_Ship_Boss_Room_W1_generators
	.byte <Level_1_Bonus_Area_W1_generators
	.byte <Level_2_Bonus_Area_W1_generators
	.byte <Default_Level_85_generators
	.byte <Level_2_Ending_W6_generators
	.byte <Level_4_Ending_W1_generators
	.byte <Dungeon_Spike_Room_W1_generators
	.byte <Level_5_Bonus_W1_generators
	.byte <Level_2_Ending_W2_generators
	.byte <Level_3_Ending_W2_generators
	.byte <Level_1_Bonus_Area_W2_generators
	.byte <Dungeon_Spike_Room_W2_generators
	.byte <Level_5_Bonus_Area_W2_generators
	.byte <Pyramid_W2_generators
	.byte <Level_3_Ending_W3_generators
	.byte <Level_2_Ending_W3_generators
	.byte <Dungeon__1_Water_Room_W3_generators
	.byte <Level_2_Ending_W7_generators
	.byte <Level_5_Ending_W3_generators
	.byte <Level_6_Ending_W3_generators
	.byte <Level_7_Bonus_Area_W3_generators
	.byte <Level_8_Ending_W3_generators
	.byte <Dungeon__2_Water_Room_W3_generators
	.byte <Level_9_Ending_W3_generators
	.byte <Level_6_Small_Side_W4_generators
	.byte <Dungeon__2_Pipe_Room_W4_generators
	.byte <Level_5_Bonus_Area_W4_generators
	.byte <Dungeon__1_Underground_Room_W4_generators
	.byte <Level_3_W4_generators
	.byte <Default_Level_166_generators
	.byte <Level_4_Bonus_Area_W4_generators
	.byte <Level_1_Bonus_Area_W4_generators
	.byte <Level_2_Pipe_Room_W5_generators
	.byte <Level_3_W5_generators
	.byte <Level_3_Ending_W5_generators
	.byte <Level_1_Bonus_Area_W5_generators
	.byte <Tower_Outside_Area__Part_1__W5_generators
	.byte <Tower__Part_2__W5_generators
	.byte <Tower_Outside_Area__Part_2__W5_generators
	.byte <Dungeon__1_Bonus_Area_W5_generators
	.byte <Level_9_Ending_W5_generators
	.byte <Dungeon__2_W5_generators
	.byte <Level_7_Bonus_Area_W5_generators
	.byte <Level_1_Bonus_Area_W6_generators
	.byte <Dungeon__1_Spike_Room_W6_generators
	.byte <Level_6_W6_generators
	.byte <Dungeon__2_Boss_Room_W6_generators
	.byte <Level_4_Bonus_Area_W6_generators
	.byte <Level_7_Ending_W6_generators
	.byte <Level_5_W6_generators
	.byte <Level_9_W6_generators
	.byte <Dungeon__3_Falling_Room_W6_generators
	.byte <Dungeon__1_Lonely_Room_W7_generators
	.byte <Level_1_W7_generators
	.byte <Piranha_Plant__1_Ending_W7_generators
	.byte <Level_4_W7_generators
	.byte <Level_6_W7_generators
	.byte <Level_7_W7_generators
	.byte <Level_8_Bonus_Area__1_W7_generators
	.byte <Level_5_W7_generators
	.byte <Level_9_Ending_W7_generators
	.byte <Dungeon__2_Boss_Room_W7_generators
	.byte <Piranha_Plant__2_Ending_W7_generators
	.byte <Tank__1_Boss_Room_W8_generators
	.byte <Battleship_Boss_Room_W8_generators
	.byte <Hand_Trap__3_Ending_W8_generators
	.byte <Dungeon__White_Side__W8_generators
	.byte <Default_Level_297_generators
	.byte <Tank__2_Boss_Room_W8_generators
	.byte <Bowser's_Lair_W8_generators
	.byte <Default_Level_348_348_generators
	.byte <Default_Level_349_349_generators
	.byte <Default_Level_350_350_generators
	.byte <Default_Level_351_351_generators
	.byte <Default_Level_352_352_generators
	.byte <Default_Level_353_353_generators
	.byte <Default_Level_354_354_generators
	.byte <Default_Level_355_355_generators
	.byte <Default_Level_356_356_generators
	.byte <Default_Level_357_357_generators
	.byte <Default_Level_358_358_generators
	.byte <Default_Level_359_359_generators
	.byte <Default_Level_360_360_generators
	.byte <Default_Level_361_361_generators
	.byte <Default_Level_362_362_generators
	.byte <Default_Level_363_363_generators
	.byte <Default_Level_364_364_generators
	.byte <Default_Level_365_365_generators
	.byte <Default_Level_366_366_generators
	.byte <Default_Level_367_367_generators
	.byte <Default_Level_368_368_generators
	.byte <Default_Level_369_369_generators
	.byte <Default_Level_370_370_generators
	.byte <Default_Level_371_371_generators
	.byte <Default_Level_372_372_generators
	.byte <Default_Level_373_373_generators
	.byte <Default_Level_374_374_generators
	.byte <Default_Level_375_375_generators
	.byte <Default_Level_376_376_generators
	.byte <Default_Level_377_377_generators
	.byte <Default_Level_378_378_generators
	.byte <Default_Level_379_379_generators
	.byte <Default_Level_380_380_generators
	.byte <Default_Level_381_381_generators
	.byte <Default_Level_382_382_generators
	.byte <Default_Level_383_383_generators
	.byte <Default_Level_384_384_generators
	.byte <Default_Level_385_385_generators
	.byte <Default_Level_386_386_generators
	.byte <Default_Level_387_387_generators
	.byte <Default_Level_388_388_generators
	.byte <Default_Level_389_389_generators
	.byte <Default_Level_390_390_generators
	.byte <Default_Level_391_391_generators
	.byte <Default_Level_392_392_generators
	.byte <Default_Level_393_393_generators
	.byte <Default_Level_394_394_generators
	.byte <Default_Level_395_395_generators
	.byte <Default_Level_396_396_generators
	.byte <Default_Level_397_397_generators
	.byte <Default_Level_398_398_generators
	.byte <Default_Level_399_399_generators
	.byte <Default_Level_400_400_generators
	.byte <Default_Level_401_401_generators
	.byte <Default_Level_402_402_generators
	.byte <Default_Level_403_403_generators
	.byte <Default_Level_404_404_generators
	.byte <Default_Level_405_405_generators
	.byte <Default_Level_406_406_generators
	.byte <Default_Level_407_407_generators
	.byte <Default_Level_408_408_generators
	.byte <Default_Level_409_409_generators
	.byte <Default_Level_410_410_generators
	.byte <Default_Level_411_411_generators
	.byte <Default_Level_412_412_generators
	.byte <Default_Level_413_413_generators
	.byte <Default_Level_414_414_generators
	.byte <Default_Level_415_415_generators
	.byte <Default_Level_416_416_generators
	.byte <Default_Level_417_417_generators
	.byte <Default_Level_418_418_generators
	.byte <Default_Level_419_419_generators
	.byte <Default_Level_420_420_generators
	.byte <Default_Level_421_421_generators
	.byte <Default_Level_422_422_generators
	.byte <Default_Level_423_423_generators
	.byte <Default_Level_424_424_generators
	.byte <Default_Level_425_425_generators
	.byte <Default_Level_426_426_generators
	.byte <Default_Level_427_427_generators
	.byte <Default_Level_428_428_generators
	.byte <Default_Level_429_429_generators
	.byte <Default_Level_430_430_generators
	.byte <Default_Level_431_431_generators
	.byte <Default_Level_432_432_generators
	.byte <Default_Level_433_433_generators
	.byte <Default_Level_434_434_generators
	.byte <Default_Level_435_435_generators
	.byte <Default_Level_436_436_generators
	.byte <Default_Level_437_437_generators
	.byte <Default_Level_438_438_generators
	.byte <Default_Level_439_439_generators
	.byte <Default_Level_440_440_generators
	.byte <Default_Level_441_441_generators
	.byte <Default_Level_442_442_generators
	.byte <Default_Level_443_443_generators
	.byte <Default_Level_444_444_generators
	.byte <Default_Level_445_445_generators
	.byte <Default_Level_446_446_generators
	.byte <Default_Level_447_447_generators
	.byte <Default_Level_448_448_generators
	.byte <Default_Level_449_449_generators
	.byte <Default_Level_450_450_generators
	.byte <Default_Level_451_451_generators
	.byte <Default_Level_452_452_generators
	.byte <Default_Level_453_453_generators
	.byte <Default_Level_454_454_generators
	.byte <Default_Level_455_455_generators
	.byte <Default_Level_456_456_generators
	.byte <Default_Level_457_457_generators
	.byte <Default_Level_458_458_generators
	.byte <Default_Level_459_459_generators
	.byte <Default_Level_460_460_generators
	.byte <Default_Level_461_461_generators
	.byte <Default_Level_462_462_generators
	.byte <Default_Level_463_463_generators
	.byte <Default_Level_464_464_generators
	.byte <Default_Level_465_465_generators
	.byte <Default_Level_466_466_generators
	.byte <Default_Level_467_467_generators
	.byte <Default_Level_468_468_generators
	.byte <Default_Level_469_469_generators
	.byte <Default_Level_470_470_generators
	.byte <Default_Level_471_471_generators
	.byte <Default_Level_472_472_generators
	.byte <Default_Level_473_473_generators
	.byte <Default_Level_474_474_generators
	.byte <Default_Level_475_475_generators
	.byte <Default_Level_476_476_generators
	.byte <Default_Level_477_477_generators
	.byte <Default_Level_478_478_generators
	.byte <Default_Level_479_479_generators
	.byte <Default_Level_480_480_generators
	.byte <Default_Level_481_481_generators
	.byte <Default_Level_482_482_generators
	.byte <Default_Level_483_483_generators
	.byte <Default_Level_484_484_generators
	.byte <Default_Level_485_485_generators
	.byte <Default_Level_486_486_generators
	.byte <Default_Level_487_487_generators
	.byte <Default_Level_488_488_generators
	.byte <Default_Level_489_489_generators
	.byte <Default_Level_490_490_generators
	.byte <Default_Level_491_491_generators
	.byte <Default_Level_492_492_generators
	.byte <Default_Level_493_493_generators
	.byte <Default_Level_494_494_generators
	.byte <Default_Level_495_495_generators
	.byte <Default_Level_496_496_generators
	.byte <Default_Level_497_497_generators
	.byte <Default_Level_498_498_generators
	.byte <Default_Level_499_499_generators
	.byte <Default_Level_500_500_generators
	.byte <Default_Level_501_501_generators
	.byte <Default_Level_502_502_generators
	.byte <Default_Level_503_503_generators
	.byte <Default_Level_504_504_generators
	.byte <Default_Level_505_505_generators
	.byte <Default_Level_506_506_generators
	.byte <Default_Level_507_507_generators
	.byte <Default_Level_508_508_generators
	.byte <Default_Level_509_509_generators
	.byte <Default_Level_510_510_generators
	.byte <Default_Level_511_511_generators
