from collections.abc import Sequence
from typing import Any, final

@final
class INESHeader:
    @property
    def chr_size(self, /) -> int: ...
    @property
    def prg_size(self, /) -> int: ...

@final
class Rom:
    def __new__(cls, /, data: Sequence[int]) -> Rom: ...
    def byte(self, /, address: Any) -> int: ...
    def find_byte(self, /, byte: int, start: Any |None, end: Any |None) -> Any |None: ...
    @staticmethod
    def from_file(path: str) -> Rom: ...
    def little_endian(self, /, address: Any) -> int: ...
    def nibbles(self, /, address: Any) -> tuple[int, int]: ...
    def offset(self, /, address: Any) -> Any: ...
    @property
    def prg_banks(self, /) -> int: ...
    def prg_normalize(self, /, address: Any) -> Any: ...
    @property
    def prg_units(self, /) -> int: ...
    def read(self, /, address: Any, count: int) -> bytes: ...
    def read_until_byte(self, /, address: Any, byte: int) -> bytes |None: ...
    def save_to(self, /, path: str) -> None: ...
    def tsa_data_for_object_set(self, /, object_set_index: Any) -> bytes: ...
    def write(self, /, address: Any, data: bytes) -> None: ...
    def write_byte(self, /, address: Any, byte: int) -> None: ...
    def write_little_endian(self, /, address: Any, integer: int) -> None: ...
    def write_nibbles(self, /, address: Any, high_nibble: int, low_nibble: int) -> None: ...
    def write_offset(self, /, address: Any, offset: Any) -> None: ...

def clamp(min: int, value: int, max: int) -> int: ...
def hex_int(number: str) -> int: ...
def apply()
