pub const WORLD_MAP_SCREEN_WIDTH: u8 = 16;
pub const WORLD_MAP_SCREEN_HEIGHT: u8 = 9;
pub const WORLD_MAP_SCREEN_SIZE: u8 = WORLD_MAP_SCREEN_WIDTH * WORLD_MAP_SCREEN_HEIGHT;
pub const FIRST_VALID_ROW: u8 = 2;
